const canvas=document.getElementById('ocean'),ctx=canvas.getContext('2d');let w,h,dpr=1,depth=0,targetDepth=0,last=0,flash=false,learn=true,active=null,visibleCreatures=[],installPrompt=null;
const creatures=[
 {id:'siph',name:'סיפונופור ענק',latin:'Siphonophorae',depth:900,size:'אורך: עשרות מטרים בפרטים חריגים',ratio:18,kind:'siph',facts:['מושבה של יחידות זעירות הפועלות יחד כאורגניזם אחד.','חלק מהמינים מפיקים אור ביולוגי.','האורכים המרביים המדווחים משתנים בין תצפיות ולכן מוצגים כהערכה.']},
 {id:'giant',name:'דיונון ענק',latin:'Architeuthis dux',depth:1200,size:'אורך כולל: עד כ־12–13 מ׳',ratio:7,kind:'squid',facts:['אחד מחסרי החוליות הארוכים בעולם.','חי בעומקים של מאות מטרים ולעיתים עמוק יותר.','העיניים שלו הן מן הגדולות בעולם החי.']},
 {id:'magna',name:'דיונון ארוך־סנפיר',latin:'Magnapinna',depth:2600,size:'אורך נצפה: כמה מטרים; הזרועות ארוכות במיוחד',ratio:5,kind:'magna',facts:['אחד הדיונונים המסתוריים ביותר של הים העמוק.','נצפה בעזרת כלי מחקר תת־ימיים בעומקים של אלפי מטרים.','הגודל המדויק קשה למדידה מתצפיות וידאו בלבד.']}
];
function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const el=id=>document.getElementById(id),depthEl=el('depth'),zoneEl=el('zone'),fill=el('depthFill'),enc=el('encounter');
function zone(d){if(d<200)return'אזור האור';if(d<1000)return'אזור הדמדומים';if(d<4000)return'אזור החצות';return'המעמקים'}
function updateHUD(){depthEl.textContent=Math.round(depth).toLocaleString('he-IL');zoneEl.textContent=zone(depth);fill.style.width=Math.min(100,depth/60)+'%';active=creatures.find(x=>Math.abs(depth-x.depth)<240)||null;enc.classList.add('hidden')}
function bg(){const t=Math.min(depth/6000,1);const top=[4,39,65],bot=[0,5,13];const r=Math.round(top[0]*(1-t)+bot[0]*t),g=Math.round(top[1]*(1-t)+bot[1]*t),b=Math.round(top[2]*(1-t)+bot[2]*t);ctx.fillStyle=`rgb(${r},${g},${b})`;ctx.fillRect(0,0,w,h);for(let i=0;i<34;i++){const y=(i*73+(performance.now()/70)*(i%3+1))%h,x=(i*131)%w;ctx.fillStyle='rgba(180,225,245,'+(0.03+(i%5)*.01)+')';ctx.beginPath();ctx.arc(x,y,1+(i%3),0,Math.PI*2);ctx.fill()}}
function drawSquid(x,y,s,magna=false){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.fillStyle=learn?'rgba(150,210,235,.92)':'rgba(83,125,145,.72)';ctx.beginPath();ctx.ellipse(0,0,38,20,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-18,-12);ctx.lineTo(-44,-30);ctx.lineTo(-34,-4);ctx.fill();ctx.lineWidth=2;ctx.strokeStyle=ctx.fillStyle;const len=magna?95:58;for(let i=-3;i<=3;i++){ctx.beginPath();ctx.moveTo(32,i*3);ctx.quadraticCurveTo(58+i*2,20+i*3,len,42+i*5);ctx.stroke()}ctx.restore()}
function drawSiph(x,y,s){ctx.save();ctx.translate(x,y);ctx.strokeStyle=learn?'rgba(130,245,224,.9)':'rgba(80,150,145,.65)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-110*s,0);for(let i=-110;i<=110;i+=8)ctx.lineTo(i*s,Math.sin(i/16+performance.now()/700)*8*s);ctx.stroke();for(let i=-100;i<100;i+=18){ctx.fillStyle='rgba(150,255,235,.62)';ctx.beginPath();ctx.arc(i*s,Math.sin(i/16+performance.now()/700)*8*s,3*s,0,Math.PI*2);ctx.fill()}ctx.restore()}
function creatureLayer(){visibleCreatures=[];creatures.forEach((c,i)=>{const delta=Math.abs(depth-c.depth);if(delta>420)return;const a=1-delta/420;ctx.save();ctx.globalAlpha=a;const x=w*.53+Math.sin(performance.now()/1100+i)*w*.08,y=h*.48+i*22,s=Math.max(.75,Math.min(1.45,w/430));if(c.kind==='siph')drawSiph(x,y,s*.95);else drawSquid(x,y,s,c.kind==='magna');ctx.restore();visibleCreatures.push({c,x,y,r:c.kind==='siph'?Math.min(190,w*.42):115})})}
function frame(ts){const dt=Math.min((ts-last)/1000,.05)||0;last=ts;depth+=(targetDepth-depth)*Math.min(1,dt*2.4);updateHUD();bg();creatureLayer();requestAnimationFrame(frame)}requestAnimationFrame(frame);
function setDepth(v){targetDepth=Math.max(0,Math.min(6000,v));enc.classList.add('hidden')}
el('diveBtn').onclick=()=>setDepth(targetDepth+300);el('upBtn').onclick=()=>setDepth(targetDepth-300);
el('learnMode').onclick=()=>{learn=!learn;el('learnMode').setAttribute('aria-pressed',learn);el('learnMode').textContent=learn?'👁️ מצב לימודי':'🌑 מצב ריאליסטי'};
const fl=el('flashlight');el('flashlightBtn').onclick=()=>{flash=!flash;fl.style.display=flash?'block':'none';el('flashlightBtn').setAttribute('aria-pressed',flash)};
function moveLight(e){if(!flash)return;const p=e.touches?e.touches[0]:e;fl.style.left=p.clientX+'px';fl.style.top=p.clientY+'px'}addEventListener('pointermove',moveLight);addEventListener('touchmove',moveLight,{passive:true});
function openPanel(id){el('scrim').classList.remove('hidden');el(id).classList.add('open');el(id).setAttribute('aria-hidden','false')}
function closePanels(){document.querySelectorAll('.panel').forEach(p=>{p.classList.remove('open');p.setAttribute('aria-hidden','true')});el('scrim').classList.add('hidden')}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closePanels);
el('detailsBtn').onclick=()=>{if(!active)return;el('infoTitle').textContent=active.name;el('infoLatin').textContent=active.latin;el('infoBody').innerHTML=`<div class="fact"><b>גודל</b>${active.size}</div><div class="fact"><b>עומק המפגש בסימולטור</b>${active.depth.toLocaleString('he-IL')} מ׳</div>${active.facts.map((f,i)=>`<div class="fact"><b>${['מה מיוחד בו?','סביבת חיים','רמת ודאות'][i]||'מידע'}</b>${f}</div>`).join('')}<p class="note">הסימולטור הוא המחשה לימודית; עומקים וגדלים עשויים להשתנות בין פרטים ותצפיות.</p>`;openPanel('infoPanel')};
el('compareBtn').onclick=()=>{if(!active)return;el('compareTitle').textContent=active.name;el('scaleLabel').textContent=active.size;const sc=el('scaleCreature');sc.style.width=Math.min(280,70+active.ratio*13)+'px';sc.style.height=(active.kind==='siph'?18:42)+'px';openPanel('comparePanel')};
canvas.addEventListener('pointerup',e=>{const hit=visibleCreatures.find(v=>Math.hypot(e.clientX-v.x,e.clientY-v.y)<=v.r);if(!hit)return;active=hit.c;el('creatureName').textContent=active.name;el('creatureLatin').textContent=active.latin;el('creatureSize').textContent=active.size;el('detailsBtn').click()});
const installBtn=el('installBtn');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;installBtn.classList.remove('hidden')});installBtn?.addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installBtn.classList.add('hidden')});window.addEventListener('appinstalled',()=>installBtn?.classList.add('hidden'));
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js',{scope:'/'}).then(r=>r.update()).catch(()=>{}));